[project]
name = "agent-company"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "google-genai>=1.45.0",
    "pillow>=12.0.0",
    "pinterest-api-sdk>=0.2.6",
    "tweepy>=4.16.0",
]
